// <auto-generated />
using System;
using FocusHealthSolutionsTeste1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FocusHealthSolutionsTeste1.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FocusHealthSolutionsTeste1.Models.PlanilhaModel", b =>
                {
                    b.Property<int>("Ficha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASO_Prot")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ASO_Up")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("Agendado_Em")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Agendado_Para")
                        .HasColumnType("datetime2");

                    b.Property<string>("Colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conf")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Natureza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parceiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pend")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Pres")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Tem_Av")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Tem_Res")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Ficha");

                    b.ToTable("Planilha");
                });
#pragma warning restore 612, 618
        }
    }
}
