CREATE TABLE GERENTE(
CPF VARCHAR(11),
NOME VARCHAR(150),
DATA_NASCIMENTO DATE
);


ALTER TABLE GERENTE ALTER COLUMN CPF VARCHAR(11) NOT NULL;


ALTER TABLE Cadastro_Produtos ALTER COLUMN Codigo_Produto VARCHAR(20) NOT NULL;

ALTER TABLE Cadastro_Produtos ADD CONSTRAINT PK_Cadastro_Produtos PRIMARY KEY CLUSTERED ([Codigo_Produto]);

ALTER TABLE GERENTE ADD CONSTRAINT PK_GERENTE PRIMARY KEY CLUSTERED ([CPF]);

drop table GERENTE