CREATE TABLE [Cadastro_Produtos](
	CODIGO_PRODUTO VARCHAR(20) PRIMARY KEY NOT NULL,
	NOME_PRODUTO VARCHAR(150),
	EMBALAGEM VARCHAR(50),
	TAMANHO FLOAT,
	SABOR VARCHAR(50),
	PRECO_DE_LISTA SMALLMONEY
)


INSERT INTO [Cadastro_Produtos]
VALUES('1004356','LINHA CITROS','PET',1,'LIMÃO', 7.00);


INSERT INTO [Cadastro_Produtos]
VALUES('1004356','LINHA CITROS','PET',1,'LIMÃO', 7.00),
('544931','FRESCOR DO VERÃO','LATA',350,'MANGA', 5.18);


UPDATE [Cadastro_Produtos]
SET EMBALAGEM = 'PET'
WHERE CODIGO_PRODUTO = '1004356';

UPDATE [Cadastro_Produtos]
SET EMBALAGEM = 'GARRAFA', PRECO_DE_LISTA = 16.00
WHERE CODIGO_PRODUTO = '1004356';


DELETE FROM [Cadastro_Produtos]
WHERE CODIGO_PRODUTO = '1004327';


ALTER TABLE [Cadastro_Produto] ALTER COLUMN NOME_COMPLETO VARCHAR(200);


SELECT * FROM [Cadastro_Produtos];

SELECT CODIGO_PRODUTO, NOME_PRODUTO AS PRODUTO FROM Cadastro_Produtos;

SELECT * FROM [Cadastro_Produtos] WHERE [CODIGO_PRODUTO] = '1004356';

--DROP TABLE [Cadastro_Produtos];